### ISSUE TITLE
Inliner v2 error coding & and template {{#each}} tags

### ISSUE THREAD

**Issue by esteban-maidana** [foundation/foundation-emails#335] opened 2016-04-08 02:10 UTC
Hello, i'm having some problems with the inlined code. 
1. I have already encoded &; special chars, but the inliner make it again. For example: 
    This: Products `&amp;` Services
    Turns: Products `&amp;amp;` Services
2. I have some `{{#each}}`tags using mustachio template language; it remains in the code but not a the same place. For example:

```
This:
<tbody>
    {{#each order_items}}
    <tr class="row">
        <td class="width-75">{{{item_description}}}</td>
        <td class="text-right"><small>{{{../../order_currency}}}</small> {{{item_price}}}</td>
    </tr>
    {{/each}}
</tbody>
```

```
Turns:
{{#each order_items}} {{/each}}
<tbody>
      <tr class="row" style="padding: 0; ........
        <td class="width-75" style="Margin:........
        <td class="text-right".........
      </tr>
</tbody>
```

**How can we reproduce this bug?**

I attached the html and css into this message.

**What did you expect to happen?**

If I already have an encode `&;`tag, then, the inliner do not needs to encode the & char again.

And, it would be nice if the inliner place the `{{#each}}` tags in the correct (original) places

**What happened instead?**

For `&amp;` I got `&amp;amp;`

The {{#each}} tags places (open and close) before the right place. 

**What email clients does this happen in?**

This problems are present in the inlined html generated.

[email.zip](https://github.com/zurb/foundation-emails/files/209511/email.zip)

**Comment by DanielRuf** [comment] 2018-03-11 21:34
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.

**Comment by esteban-maidana** [comment] 2018-03-12 10:17
Hello,

#335 (mine) --> esteban-maidana opened this issue on 7 Apr 2016
#841 --> afterbit01 opened this issue on 30 Oct 2017

Regards,


Esteban Maidana


2018-03-11 18:34 GMT-03:00 Daniel Ruf <notifications@github.com>:

**Comment by DanielRuf** [comment] 2018-03-12 10:18
We will track this in the latest related issue which is https://github.com/zurb/foundation-emails/issues/841

**Comment by esteban-maidana** [comment] 2018-03-12 10:19
Ok. Thanks.

**Closed as completed** 2018-03-12 10:20 UTC
Labels: inliner
