### ISSUE TITLE
Elements within curly braces are removed

### ISSUE THREAD

**Issue by markholmes** [foundation/foundation-emails#242] opened 2016-03-15 19:33 UTC
I'm not exactly sure when or where this occurs yet, but I've noticed that if there is any information between curly braces, such as `{hello}`, it is stripped out and removed in the `dist/index.html` file on save. Is this an intended behavior, or a side effect of something that I'm unaware of?

**Comment by rafibomb** [comment] 2016-03-15 23:58
Are you using `npm run build`? Or are you seeing them removed in the dist file when running `npm start`?

**Comment by rafibomb** [comment] 2016-03-16 00:02
Perhaps it's related to https://github.com/zurb/foundation-emails/issues/221 and this one has a solution.

**Comment by markholmes** [comment] 2016-03-16 15:06
@rafibomb They are removed whether I use `npm run build` or `npm start`. I tried @gakimball's suggestion in #221 but it didn't work for me -- it's possible that I misunderstood the instructions, though.

**Comment by gakimball** [comment] 2016-03-16 16:06
Closing in favor of #221. I'll test the solution I put together there and see what the problem is.

**Closed as completed by gakimball** 2016-03-16 16:06 UTC
