### ISSUE TITLE
' gets replace with &apos; this doesn't work on outlook should switch it to &#8217;

### ISSUE THREAD

**Issue by bc-ian** [foundation/foundation-emails#337] opened 2016-04-11 17:29 UTC
the inliner replaces ' with `&apos;` which doesnt get recognized on outlook.com

I suggest that this gets changed to `&#8217;` which is the equivalent, and works across all mail clients.

**Comment by ableandre** [comment] 2016-05-02 18:53
I'm having the same issue when inlining and then sending tests to Windows 10 Mail and Outlook Webmail — `&apos` doesn't work in Outlook. I've found that Mailchimp adds the `&#39;` entity when updating text in their tool, and it works fine. I'm also fine with `&#8217;`

![screen shot 2016-05-02 at 11 52 31 am](https://cloud.githubusercontent.com/assets/6910509/14964304/68bb0ff0-105c-11e6-868c-5efb27c221c5.png)

**Comment by rafibomb** [comment] 2016-05-05 20:32
Which inliner are you using? Can you share a link?

**Comment by rafibomb** [comment] 2016-05-05 22:04
Looks like an Inky issue with Cherio. This is a duplicate of https://github.com/zurb/foundation-emails/issues/281 so we'll close this one so you can follow on there. Thanks!

**Closed as completed by rafibomb** 2016-05-05 22:04 UTC
Labels: bug, inliner

**Comment by rafibomb** [comment] 2016-06-20 20:11
Resolved by https://github.com/zurb/inky/pull/57
