### ISSUE TITLE
Ampersands are converted by inliner

### ISSUE THREAD

**Issue by weishiji** [foundation/foundation-emails#305] opened 2016-03-30 03:19 UTC
npm run build
 `&` will be Translation to `&amp;`
but i do not want to do this

**Comment by rafibomb** [comment] 2016-03-30 18:12
This is pretty standard. If they are converted, does it cause an issue when sending?

**Comment by weishiji** [comment] 2016-03-31 02:00
I use a third party platform to send email,but the platform may be has some
problem.I send the building content to customers with the platform,when
customers open the link in email,the link has amp; in address bar.so i used
gulp-replace plugin to replace them,and it can work

2016-03-31 2:12 GMT+08:00 Rafi notifications@github.com:

> This is pretty standard. If they are converted, does it cause an issue
> when sending?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/zurb/foundation-emails/issues/305#issuecomment-203561073

## 

姓名：刘小光
电话：18610078527

**Comment by rafibomb** [comment] 2016-03-31 20:21
I see, thanks! We're going to be changing how that works for the next patch.

**Comment by weishiji** [comment] 2016-04-01 01:36
Thank you! I want to  add a optional parameters in command to decide whether  the link is converted.

**Comment by rafibomb** [comment] 2016-04-25 21:10
@kball This may be happening on the web inliner. Can you take a look?

**Comment by alex-ketch** [comment] 2016-07-09 20:19
~~Just to note, this is also causing issues when trying to write ampersand escaped characters.
So `&copy;` becomes `&amp;copy;`~~

Updating to `Inky 1.3.6` solved the above mentioned problem.

**Comment by DanielRuf** [comment] 2018-03-11 21:34
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.

**Closed as completed** 2019-11-01 18:39 UTC
Labels: inliner
