### ISSUE TITLE
HTML File Sizes, Not view entire message in Gmail, Yahoo, Hotmail.

### ISSUE THREAD

**Issue by ralts00** [foundation/foundation-emails#529] opened 2016-07-17 23:32 UTC
When the file genres in Production, Gmail and other mail clients shorten the Message.

![captura de pantalla 2016-07-17 18 21 46](https://cloud.githubusercontent.com/assets/5034252/16903720/80f23bf4-4c4b-11e6-8eba-775b94aae575.png)

rule 102KB exceed, Here's a post about what is happening equal 
http://foundation.zurb.com/forum/posts/45058-html-file-sizes-with-foundation-for-emails

magnifico serious that can help minimize the file, or to notify us if the file is not complete in some clients show

excuse my English , I'm using a translator :)

[tips_mx.html.zip](https://github.com/zurb/foundation-emails/files/368183/tips_mx.html.zip)

**Comment by rafibomb** [comment] 2016-07-21 05:22
That's right - Gmail has a character and file size limit for the HTML. This does NOT include images. The best way to help with this is to make sure you are compressing the whitespace in your emails. The inliner has an option for that. If you are using the ZURB Stack, the template is configured to do so automatically.

**Comment by rafibomb** [comment] 2016-07-21 05:29
It's not a bug so we'll close this here. Let's keep the discussion going on the forum post http://foundation.zurb.com/forum/posts/45058-html-file-sizes-with-foundation-for-emails I posted some suggestions and we can bounce around ideas!

**Closed as completed by rafibomb** 2016-07-21 05:29 UTC
