### ISSUE TITLE
Inliner replacing & with &amp;

### ISSUE THREAD

**Issue by nicolajcimino** [foundation/foundation-emails#610] opened 2016-10-13 13:22 UTC
**How can we reproduce this bug?**
HTML that is inserted with `&` within seems to have it "auto-fixed" to `&amp;` regardless of whether that is the appropriate syntax or not. `&amp;` in code results in `&amp;amp;` I've also seen it add it to `&nbsp;` also resulting in `&amp;nbsp;`.

Write out the HTML (or Inky code) that causes the issue.

**What did you expect to happen?**
I expected it to ignore &'s resulting in the code originally written.

**What happened instead?**
It was auto-fixed `&` to `&amp`;

**What email clients does this happen in?**
all

**Comment by nicolajcimino** [comment] 2016-10-25 18:46
I've noticed that this problem only seems to happen when you click on the copy to clipboard button

**Comment by rafibomb** [comment] 2016-11-01 00:15
Looks like a duplicate of https://github.com/zurb/foundation-emails/issues/334. Closing in favor of it.

**Closed as completed by rafibomb** 2016-11-01 00:15 UTC
