### ISSUE TITLE
cannot run foundation watch as it stops at tasks not completed pages, javascript, copy

### ISSUE THREAD

**Issue by JulioBastidas** [foundation/foundation-emails#998] opened 2020-03-28 22:39 UTC
Hi i was working on a project normally using foundation watch on the cmd on windows but at the next day it just stopped working:

> foundation-zurb-template@1.0.0 start E:\Uni\Cursos\cafeteria
> gulp

[17:35:52] Requiring external module @babel/register
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
[17:35:54] Using gulpfile E:\Uni\Cursos\cafeteria\gulpfile.babel.js
[17:35:54] Starting 'default'...
[17:35:54] Starting 'build'...
[17:35:54] Starting 'clean'...
[17:35:54] Finished 'clean' after 2.82 ms
[17:35:54] Starting 'pages'...
[17:35:54] Starting 'javascript'...
[17:35:54] Starting 'images'...
[17:35:54] Starting 'copy'...
[17:35:54] 'images' errored after 185 ms
[17:35:54] TypeError: $.imagemin.jpegtran is not a function
    at images (E:\Uni\Cursos\cafeteria\/gulpfile.babel.js:144:18)
    at bound (domain.js:402:14)
    at runBound (domain.js:415:12)
    at asyncRunner (E:\Uni\Cursos\cafeteria\node_modules\async-done\index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[17:35:54] 'build' errored after 200 ms
[17:35:54] 'default' errored after 202 ms
[17:35:54] The following tasks did not complete: pages, javascript, copy
[17:35:54] Did you forget to signal async completion?
Error: foundation-zurb-template@1.0.0 start: `gulp`
Exit status 1
    at EventEmitter.<anonymous> (C:\Program Files\node-v10.19.0-win-x64\node_modules\foundation-cli\node_modules\npm\lib\utils\lifecycle.js:217:16)
    at EventEmitter.emit (events.js:198:13)
    at ChildProcess.<anonymous> (C:\Program Files\node-v10.19.0-win-x64\node_modules\foundation-cli\node_modules\npm\lib\utils\spawn.js:24:14)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

i did not install something else and i did a system point recovery to install all again normally but now it seems like it stopped working.

npm version: 6.13..4

node version: 10.19.0

python 2.7.17

foundation CLI version 2.2.5

**Comment by DanielRuf** [comment] 2020-03-29 00:57
Duplicate of the other issue in foundation-sites.

> TypeError: $.imagemin.jpegtran is not a function

**Closed as completed by DanielRuf** 2020-03-29 00:57 UTC
