### ISSUE TITLE
Online Inliner converts &nbsp; to  &amp;nbsp;

### ISSUE THREAD

**Issue by antonseitz** [foundation/foundation-emails#549] opened 2016-08-05 17:35 UTC
**How can we reproduce this bug?**

I wanted to convert my email-layout based on your example template "newsletter.html" with 

http://foundation.zurb.com/emails/inliner-v2.html

In newsletter.html there is:

```
<h1 class="text-center">The Insider</h1>
                                  <center data-parsed=""> <img src="http://placehold.it/500x200" align="center" class="float-center"> </center>
                                  <table class="spacer">
                                    <tbody>
                                      <tr>
                                        <td height="16px" style="font-size:16px;line-height:16px;">&#xA0;</td>
```

**What did you expect to happen?**
I expected `&#xA0;`to be also in the "Final Email HTML"-output.

**What happened instead?**

The `&#xA0;` was converted to 
`&nbsp;`

But if even worse:

After clicking "Copy to Clipboard" and pasting it in my editor it was converted to:
`&amp;nbsp;`

```
                          <td style="-moz-hyphens: auto; -webkit-hyphens: auto; Margin: 0; border-collapse: collapse !important; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; hyphens: auto; line-height: 16px; margin: 0; mso-line-height-rule: exactly; padding: 0; text-align: left; vertical-align: top; word-wrap: break-word;"
                            height="16px">&amp;nbsp;</td>
                        </tr>
                      </tbody>
```

**What email clients does this happen in?**

No mail client was involved. It happend using your online Inline-Tool
http://foundation.zurb.com/emails/inliner-v2.html

**Comment by richbothe** [comment] 2016-08-25 15:08
I am having this issue as well. When I enter either a regular space (spacebar) or add `&nbsp;` my dist file shows `&#xA0;` while Chrome inspector shows `&nbsp;`.

**Comment by penguin20000** [comment] 2016-09-05 21:06
Same issue here.

**Comment by maxms** [comment] 2016-09-15 18:19
+1

**Comment by bharlson** [comment] 2017-05-31 20:25
Same issue here

**Comment by bravo-kernel** [comment] 2017-08-23 15:04
FWIW I am encountering the same issue. This is produced using latest `static-templates` and the online v2 inliner:

![image](https://user-images.githubusercontent.com/230500/29622939-10f33076-8825-11e7-8715-d5871891178a.png)

**Comment by hardcodet** [comment] 2017-10-24 20:59
Still an issue... I'm using a vanilla template with some adjustments that I just ran through the Inliner.

**Edit:** Turns out it's the `Copy` button on the inliner. Manually selecting the inlined markup and copy/pasting it got me valid markup. FF 56.0, Win 10 x64.

**Comment by bravo-kernel** [comment] 2017-10-24 21:43
@hardcodet this won’t help with the online version but once I switched to the local tool I was surprised how much easier/better that was compared to the idea I had of the online tool. The issue does not occur on the local version either.

**Comment by DanielRuf** [comment] 2018-03-11 21:58
Duplicate of #841, can be closed.

**Closed as completed** 2019-11-01 18:39 UTC
Labels: inliner
