### ISSUE TITLE
QUESTION: DOS/UNIX Line Endings

### ISSUE THREAD

**Issue by atempel** [foundation/foundation-emails#853] opened 2017-11-23 19:58 UTC
**How can we reproduce this bug?**
On a **Mac OSX** (I'm using High Sierra 10.13), from Foundation CLI (2.2.5), create a new Foundation for Emails (2.2.1) and run `npm start` on the project folder to start working on it.
The prompt throws an error with: `Env node\r: No such file or directory`

**What did you expect to happen?**
The build should run normally, opening the browser.

**What happened instead?**
The prompt returns an error due to DOS line endings.

Every time I create a new project I need to use a program like `dos2unix` to convert the whole `node_modules` folder to UNIX line endings...  Is there a fix for this on the package level or we must do this every time?

I tried to find any other issue here about that and couldn't find any... Am I the only one having this issue?

**Comment by nikitasol** [comment] 2018-02-14 23:27
Hello @atempel,

You probably have already solved the issue, but most likely it was due to a bad node/npm installation. You should probably check with Node.js repository if you are still having the issue.

**Comment by DanielRuf** [comment] 2019-12-20 09:23
Closing as this is nothing that is caused by us.

**Closed as completed by DanielRuf** 2019-12-20 09:23 UTC
