### ISSUE TITLE
Responsive Email Inliner Converts &nbsp; to &amp;nbsp; Upon Clicking "Copy to Clipboard" 

### ISSUE THREAD

**Issue by jlafica** [foundation/foundation-emails#524] opened 2016-07-12 18:20 UTC
**How can we reproduce this bug?**

Write out the HTML (or Inky code) that causes the issue.

`&nbsp;`

**What did you expect to happen?**

`&nbsp;` should be preserved as a valid html character code

**What happened instead?**

Upon clicking "Copy to Clipboard", the `&nbsp;` is converted to `&amp;nbsp;`
You can't see it in the browser window in the output frame from the tool, but if you paste the text from the clipboard into a text editor, the error appears.

`&amp;nbsp;`

**What email clients does this happen in?**

Not specific to any email client. This issue exists in the online version of the inliner.

**Comment by HHawk** [comment] 2016-08-04 09:17
I have noticed the same. Seems like a bug.
...weird that nobody else followed up on this though.

I am currently removing those by hand. But doing that several times, is a bit annoying. Oh well.

**Comment by jlafica** [comment] 2016-08-05 00:45
Agreed. Just find and replace for now I guess. Should be an easy enough bug to fix. Hopefully soon!

**Comment by DanielRuf** [comment] 2018-03-11 21:36
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.

**Closed as completed** 2019-11-01 18:39 UTC
Labels: bug, inliner
