### ISSUE TITLE
Inliner "Copy to clipboard" changes HTML-Formatting 

### ISSUE THREAD

**Issue by Tilogorn** [foundation/foundation-emails#665] opened 2016-12-13 12:26 UTC
Simply paste some HTML like the following in the Inliner HTML area and inline it:

```
<p>Me, Myself & I</p>
```

The corresponding inlined HTML looks like this, which is fine:

```
[...]
<p>Me, Myself &amp; I</p>
[...]
```

The "&" has been escaped. 
Then I want to **copy**  it with the "Copy to clipboard" button, which leads to this result:

```
[...]
<p>Me, Myself &amp;amp; I</p>
[...]
```

Seems that the HTML code was escaped again and is then incorrect.

**Comment by DanielRuf** [comment] 2018-03-11 21:41
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.

**Closed as completed** 2019-11-01 18:39 UTC
