### ISSUE TITLE
HTML elements being re-encoded

### ISSUE THREAD

**Issue by getandyjones** [foundation/foundation-emails#730] opened 2017-03-14 10:31 UTC
Further to my previous issue - it seems it's re-encoding all HTML elements - the problem is that a lot of email coders will type &amp; instead of & naturally, - and all this gets re-encoded - is there any way encoded elements can be ignored?

**Comment by DanielRuf** [comment] 2018-03-11 21:33
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.

**Closed as completed** 2019-11-01 18:39 UTC
Labels: Inky
