### ISSUE TITLE
Copy To Clipboard" button double-HTML-encodes ampersands

### ISSUE THREAD

**Issue by twiginteractive** [foundation/foundation-emails#334] opened 2016-04-07 16:41 UTC
The "Copy To Clipboard" button double-HTML-encodes entities (certainly the ampersand &).

http://foundation.zurb.com/emails/inliner-v2.html
Easily reproduced - just type '&' into the left side, hit "INLINE" then hit "Copy To Clipboard".

Paste your clipboard into notepad and see the & -> &amp; -> &amp;amp;

**Comment by rafibomb** [comment] 2016-04-25 20:59
Weird - It might be the clipboard.js plugin causing it but I'm not seeing any open issues on their end.

@kball Can you take a look on this?

**Comment by twiginteractive** [comment] 2017-01-20 16:10
I can't believe I opened this bug 9 months ago, and it's still not fixed. Especially since the provided template CSS files include `&#xA0;` in the spacer table!

**Comment by luatnd** [comment] 2017-04-19 03:48
Yep this bug is still alive 😺

**Comment by DanielRuf** [comment] 2018-03-11 21:58
Duplicate of #841, can be closed.

**Closed as completed** 2019-11-01 18:39 UTC
Labels: bug, inliner
