### ISSUE TITLE
[Getting Started with Sass] Watch fails in WSL

### ISSUE THREAD

**Issue by endymion1818** [foundation/foundation-emails#643] opened 2016-11-25 14:50 UTC
Hi guys, really impressed with your cli and tools for email authoring - I haven't used Ink for a year or so and you've improved it so much!

**How can we reproduce this bug?**

I have the dubious privilege of being a windows user (at work). I typically use WSL ("bash for windows") but have encountered the following error when running `foundation watch` on a new project:

```
$ foundation watch                                        ruby-2.3.3 python-2.7.6

> foundation-emails-template@1.0.0 start /mnt/c/Users/Developer/Sites/it-newsletter-template/it-newsletter-3
> gulp

[14:42:54] Requiring external module babel-register
/mnt/c/Users/Developer/Sites/it-newsletter-template/it-newsletter-3/node_modules/browser-sync/node_modules/dev-ip/lib/dev-ip.js:21
    var networkInterfaces = require("os").networkInterfaces();
                                          ^

Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at getIp (/mnt/c/Users/Developer/Sites/it-newsletter-template/it-newsletter-3/node_modules/browser-sync/node_modules/dev-ip/lib/dev-ip.js:21:43)
    at Object.<anonymous> (/mnt/c/Users/Developer/Sites/it-newsletter-template/it-newsletter-3/node_modules/browser-sync/lib/utils.js:4:38)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/c/Users/Developer/Sites/it-newsletter-template/it-newsletter-3/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
Error: foundation-emails-template@1.0.0 start: `gulp`
Exit status 1
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/lifecycle.js:217:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/spawn.js:24:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
It looks to me from the interface that it's looking for some sockets that aren't supported in WSL yet. Not sure actually if this should be reported to you or the WSL team. Please close if that's the case.

I've switched to Power Shell and everything's working as expected, just thought Id mention it to you.

Regards

Ben

**Comment by DanielRuf** [comment] 2018-03-11 22:00
Never seen this. Might be a general issue with Node.js on Windows.

**Comment by DanielRuf** [comment] 2019-12-20 09:25
Closing as this is not caused by us.

**Closed as completed by DanielRuf** 2019-12-20 09:25 UTC

**Comment by endymion1818** [comment] 2019-12-20 13:46
Oh wow yeah sure 👍
