### ISSUE TITLE
Please stop changing any instance of "&" to "&amp;"

### ISSUE THREAD

**Issue by samuelarchibald** [foundation/foundation-emails#383] opened 2016-04-25 18:24 UTC
Like any good web developer, I put "&amp;" in my code when I want "&" to show up. But when I put this through your inliner, it comes up as "&amp;amp;". This is ridiculous. not to mention the fact that & pretty much shows up fine on most clients nowadays. Please make it so that only an "&" with spaces on each side is changed to "&amp;", or just stop doing that please.

**Comment by rafibomb** [comment] 2016-04-25 21:03
Agreed! Hard to tell if this is the actual inliner or the web wrapper around it. Digging into it this week. Looks like this is a duplicate of https://github.com/zurb/foundation-emails/issues/305 so we'll close in favor of it. Thanks!

**Closed as completed by rafibomb** 2016-04-25 21:03 UTC
