### ISSUE TITLE
Columns should wrap on overflow i.e. >12

### ISSUE THREAD

**Issue by iamsankalp** [foundation/foundation-emails#469] opened 2016-06-13 16:19 UTC
Just wondering if it is possible to have columns adding upto more than 12 for "large" be wrapping up automatically into next line (row but not technically)?

**How can we reproduce this bug?**

```
<row>
   <columns large="6">
      Something
   </columns>
   <columns large="6">
      Something
   </columns>
   <columns large="6">
      Something
   </columns>
</row>

```

![artboard 1 copy](https://cloud.githubusercontent.com/assets/1756637/16014825/899f9220-31b0-11e6-8d54-e4cd8e6e299d.png)

![artboard 1](https://cloud.githubusercontent.com/assets/1756637/16014837/93a0389c-31b0-11e6-89f8-9caefad01cd5.png)

**What did you expect to happen?**

Column to wrap and go into second line.

**What happened instead?**

Shrunk to fit.

**What email clients does this happen in?**

Browser

**Comment by rafibomb** [comment] 2016-06-13 19:02
Hi Ian,
You can make this happen by media query

```
<row>
  <columns small="6" large="4">
    <img src="http://placeholder.pics/svg/300/FF3422-FFF936/FCFCFC/%23Swerve" alt="">
  </columns>
  <columns small="6" large="4">
    <img src="http://placeholder.pics/svg/300/FF3422-FFF936/FCFCFC/%23Swerve" alt="">
  </columns>
  <columns small="6" large="4">
    <img src="http://placeholder.pics/svg/300/FF3422-FFF936/FCFCFC/%23Swerve" alt="">
  </columns>
</row>
```

But if you're looking to do this based on available space, you can use the block grid instead but it doesn't work like Foundation for Sites where it's inline-block.

**Comment by rafibomb** [comment] 2016-06-16 17:59
@iamsankalp Does this help your situation?

**Comment by iamsankalp** [comment] 2016-06-17 10:29
@rafibomb I wanted it to work like Foundation for Sites because right now, essentially I'll need to create two separate rows of 2 elements each if i want all 4 elements to be large="6" and small="6".

I'm not sure if something could be done though. Thanks a lot for getting back, anyway! :)

**Comment by rafibomb** [comment] 2016-06-22 17:00
I see - I don't know of a way to create a block grid like in Foundation for Sites in an email. The problem is that table do not use floats like the the Sites grid, so there is no way to universally force items to stack if the run out of room. If you see an example out there that does this, please share it so we can get this feature in!

**Comment by rafibomb** [comment] 2016-06-22 17:36
So far - this is what I've come up with:

```
<style>
    /* Image Gallery CSS */
    @media only screen and (max-width: 632px) {
      td[class="img-gallery"] td {
        display: inline-block;
      }
    }
</style>


<container>
  <table cellpadding="0" cellspacing="0">
    <tr>
      <td class="img-gallery">
        <table cellpadding="0" cellspacing="0" width="100%">
          <tr>
            <td align="center" style="padding: 15px 40px 15px 0;">
              <img src="http://placehold.it/50x30&text=Main+CTA" alt="">
            </td>
            <td align="center" style="padding: 15px 40px 15px 0;">
              <img src="http://placehold.it/80x90&text=Main+CTA" alt="">
            </td>
            <td align="center" style="padding: 15px 40px 15px 0;">
              <img src="http://placehold.it/60x20&text=Main+CTA" alt="">
            </td>
            <td align="center" style="padding: 15px 40px 15px 0;">
              <img src="http://placehold.it/20x45&text=Main+CTA" alt="">
            </td>
            <td align="center" style="padding: 15px 40px 15px 0;">
              <img src="http://placehold.it/45x45&text=Main+CTA" alt="">
            </td>
            <td align="center" style="padding: 15px 40px 15px 0;">
              <img src="http://placehold.it/60x10&text=Main+CTA" alt="">
            </td>
            <td align="center" style="padding: 15px 40px 15px 0;">
              <img src="http://placehold.it/75x75&text=Main+CTA" alt="">
            </td>
            <td align="center" style="padding: 15px 0 15px 0;">
              <img src="http://placehold.it/60x30&text=Main+CTA" alt="">
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</container>
```

If this works on all email clients, we'd love to get this added in. Is something you can work into the Block Grid feature?

**Comment by lukepeach** [comment] 2016-08-02 00:07
adding a media query for smaller devices and using `display: inline-block !important;` should do the trick. it did it for me

**Comment by houmark** [comment] 2016-09-14 15:28
@rafibomb @lukepeach the media query trick does not work for me in gmail web. It will show all images in the gallery on the same line making all images super small (especially if you have a lot of images). Did you find a way to solve that?

**Comment by tdhartwick** [comment] 2016-09-15 23:31
Hi guys! Good news is on the way, Gmail will be supporting media queries so @houmark, you should be in the clear shortly - hang tight. 

this is similar to the block-grid approach, however, we had to ditch it based on Outlook 2007/10/13 causing massive issues. Gmail is now supporting `display` properties, so based on your audience demographic a `display: inline-block;` might actually work. 

Here's the announcement from google: http://googleappsdeveloper.blogspot.com/2016/09/your-emails-optimized-for-every-screen-with-responsive-design.html

Closing for now! Please reopen if there are still issues!

**Closed as completed by tdhartwick** 2016-09-15 23:31 UTC

**Comment by houmark** [comment] 2016-09-15 23:35
That's great news @tdhartwick — though I could not read out of the blog post itself that gmail web will also be supported, but hopefully that's the case.

**Comment by tdhartwick** [comment] 2016-09-16 00:13
Yep! The announcement referred to "Gmail" but the gif showing off what a responsive email is, shows it on a native app. :)
