### ISSUE TITLE
[Alignment] 

### ISSUE THREAD

**Issue by gdavida** [foundation/foundation-emails#923] opened 2018-11-20 19:52 UTC
**How can we reproduce this bug?**

Write out the HTML (or Inky code) that causes the issue.

**What did you expect to happen?**

**What happened instead?**

**What email clients does this happen in?**

**Comment by burgiuk** [comment] 2019-12-03 12:42
@DanielRuf would it be possible to get this issue closed? I think it is a duplicate of #924

**Closed as completed** 2019-12-03 12:52 UTC
