### ISSUE TITLE
&nbsp; outputs as &amp;nbsp;

### ISSUE THREAD

**Issue by waldbach** [foundation/foundation-emails#560] opened 2016-08-18 04:08 UTC
**How can we reproduce this bug?**
Use http://foundation.zurb.com/emails/inliner-v2.html (Inliner V2)

Write out the HTML (or Inky code) that causes the issue.

**What did you expect to happen?**
`&nbsp;`(no breaking space)

**What happened instead?**
`&amp;nbsp;`
Producing `&nbsp;` on the rendered page on many locations.
The ampersand should be a & instead of `&amp;`

**What email clients does this happen in?**
See http://foundation.zurb.com/emails/inliner-v2.html

**Comment by rafibomb** [comment] 2016-08-20 00:14
Is it happening when you use the copy to clipboard button?

**Comment by waldbach** [comment] 2016-08-21 22:29
Yes, I believe so.

**Comment by cgrymala** [comment] 2016-08-22 12:15
I can confirm this as well. Yes, it's happening when I click the Copy to Clipboard button in the output window.

Also, looks like this was already reported at #549

**Comment by rafibomb** [comment] 2017-09-27 17:06
Closing for #549

**Closed as completed by rafibomb** 2017-09-27 17:06 UTC
Labels: inliner
