### ISSUE TITLE
Inliner issues

### ISSUE THREAD

**Issue by stephencrowther** [foundation/foundation-emails#499] opened 2016-07-03 18:51 UTC
When using the web inliner v2, :hover pseudo classes and @font-face declarations are removed completely

**Comment by rafibomb** [comment] 2016-07-05 21:02
Looks like a duplicate of https://github.com/zurb/foundation-emails/issues/284 - closing in favor of it. Thanks!

**Closed as completed by rafibomb** 2016-07-05 21:02 UTC
