### ISSUE TITLE
Non-breaking space incorrectly inlined

### ISSUE THREAD

**Issue by andrewchilcott** [foundation/foundation-emails#675] opened 2017-01-11 15:57 UTC
When including `&nbsp;` in html that is input into the inliner, the result is `&amp;nbsp;`

**Comment by captiva-megan** [comment] 2017-02-07 22:07
This also seems to happen with ampersands. `&amp;` becomes `&amp;amp;`

**Comment by DanielRuf** [comment] 2018-03-11 21:34
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.

**Closed as completed** 2019-11-01 18:39 UTC
