### ISSUE TITLE
linear-gradient percentages break

### ISSUE THREAD

**Issue by m0n01d** [foundation/foundation-emails#525] opened 2016-07-13 14:53 UTC
**How can we reproduce this bug?**

```
@mixin gradient-bg() {
    background-color: #1e5e75;
    background-image: linear-gradient(120deg, #006384, #026e8b 10%, #026e8b 10%, #0895a5 50%, #0896a6 51%, #0896a6 51%, #0fc7c6) !important;
}
```

**What happened instead?**
when inlined gets converted to 

```
style="background-color: #1e5e75; background-image: linear-gradient(120deg,#006384,#026e8b10%,#026e8b10%,#0895a550%,#0896a651%,#0896a651%,#0fc7c6) !important;"
```

so `#026e8b10%` should be `#026e8b 10%` and so on
it breaks the gradient, and just has a white background

**Comment by DanielRuf** [comment] 2019-12-19 06:47
Closing as duplicate of https://github.com/foundation/foundation-emails/issues/918

**Closed as completed by DanielRuf** 2019-12-19 06:47 UTC
Labels: inliner
