### ISSUE TITLE
[The Grid] Three Column Display Image Alignment Issue

### ISSUE THREAD

**Issue by thomasjrowley** [foundation/foundation-emails#481] opened 2016-06-15 20:14 UTC
I am trying to wrap my head around an issue that I am experiencing with the ever-popular Outlook email client. Specifically, I am testing for Outlook 2013 on the Windows platform. 

I am using the most current version of Ink, and I am using the Inky model with a simple three column layout. I have an image in each column followed by a paragraph of text. In each scenario, the middle column is going offset from the top of the column based on the height of the third column.

I have tried everything that I know how to do and I am really am trying not to get too hacky to fix the issue. I was hoping it would be something simple. Essentially, here is the inky code I am using...

```
<container>
    <row class="background-ltgray collapse">
        <columns small="12" large="4">
            <center><img src="https://gallery.mailchimp.com/9861b0e1e4b21dc9a169dc6c8/images/9c75e87a-c225-4af4-8391-d48975777d2e.png"></center>
            <p class="text-center">&raquo; Add This Item To Your Calendar</p>
            <br>
        </columns>
        <columns small="12" large="4">
            <center><img src="https://gallery.mailchimp.com/9861b0e1e4b21dc9a169dc6c8/images/9799149b-2e18-448d-a931-93806e5e1d6b.png"></center>
            <p class="text-center">&raquo; Event Details</p>
            <br>
        </columns>
        <columns small="12" large="4">
            <center><img src="https://gallery.mailchimp.com/9861b0e1e4b21dc9a169dc6c8/images/9e863375-36f2-40b4-98b2-aee02efcde45.png"></center>
            <p class="text-center">&raquo; Questions?<br><strong>Contact Vanessa Pellegrino</strong> <a href="mailto:vanessa.l.pellegrino@nasa.gov">Vanessa.L.Pellegrino@nasa.gov</a> or <a href="tel:+12164339721">216.433.9721</a></p>
        </columns>
    </row>
</container>
```

The middle column image is offset from the top of the row by 12px-16px.

This only occurs in Outlook 2013.

**Comment by rafibomb** [comment] 2016-06-16 17:02
Hi Thomas,
Looks like this is a duplicate of your question on the Forum http://foundation.zurb.com/forum/posts/44383-zurb-ink-image-alignment-issue

Being able to set the valign on a column is something you can do with Inky if you test out the develop branch of Inky

**Comment by rafibomb** [comment] 2016-06-16 17:07
Looks like a duplicate of https://github.com/zurb/foundation-emails/issues/460

Can you update to the develop branch and let us know how it works for you?

**Closed as completed** 2016-06-20 20:23 UTC
