### ISSUE TITLE
&nbsp; turns to &amp;nbsp;

### ISSUE THREAD

**Issue by TylerPottsDev** [foundation/foundation-emails#638] opened 2016-11-22 09:12 UTC
**How can we reproduce this bug?**
Not Sure
Write out the HTML (or Inky code) that causes the issue.
&nbsp; 
**What did you expect to happen?**
Expected it to be a blank space
**What happened instead?**
turned the code to &amp;nbsp;
**What email clients does this happen in?**
All of them

**Comment by ddiomedewaw** [comment] 2016-11-30 15:44
Equal signs turn into &#x3D;

**Comment by DanielRuf** [comment] 2018-03-11 21:34
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.

**Closed as completed** 2019-11-01 18:39 UTC
