### ISSUE TITLE
Support for HTML entities starting with an ampersand

### ISSUE THREAD

**Issue by mammalalien** [foundation/foundation-emails#981] opened 2020-01-31 00:17 UTC
**How can we reproduce this bug?**

Something about my HTML code is causing HTML entities that starts with an ampersand (&) to be broken. For example:
```
&nbsp;
&amp;
&gt;
```

…become:

```
&amp;nbsp;
&amp;amp;
&amp;gt;

```
Write out the HTML (or Inky code) that causes the issue.

See attached file:
[example-code.html.txt](https://github.com/foundation/foundation-emails/files/4136894/example-code.html.txt)

**What did you expect to happen?**

Expected HTML entities to survive inlining without modification.

**What happened instead?**

Every ampersand character is replaced with &amp; meaning that HTML entities starting with an ampersand are broken, as follows:
```
&amp;nbsp;
&amp;amp;
&amp;gt;
```

**What email clients does this happen in?**
All (not relevant, issue apparent prior to sending).

**Comment by DanielRuf** [comment] 2020-01-31 00:26
Hi @mammalalien,

please provide the steps that you took to generate the code so we can reproduce it.

Did you use the online inliner?

**Comment by DanielRuf** [comment] 2020-01-31 00:27
Also see https://github.com/foundation/foundation-emails/issues?q=is%3Aissue+sort%3Aupdated-desc+ampersand+is%3Aclosed

**Comment by DanielRuf** [comment] 2020-01-31 00:28
Duplicate of https://github.com/foundation/foundation-emails/issues/841

**Closed as completed by DanielRuf** 2020-01-31 00:28 UTC

**Comment by mammalalien** [comment] 2020-01-31 02:47
Hi @DanielRuf,

Yes, I was using this: https://foundation.zurb.com/emails/inliner-v2.html

My example code (previously attached) is a template that I just edit by hand as needed and paste into the online inliner. I copy the CSS out of the head and paste it into the CSS field too. Not sure if this is necessary. The ampersand issue happens either way.
