### ISSUE TITLE
Inliner 1.0 not working anymore

### ISSUE THREAD

**Issue by maxassante** [foundation/foundation-emails#859] opened 2017-12-18 09:52 UTC
**How can we reproduce this bug?**

Just try to use Inliner 1.0 (https://foundation.zurb.com/emails/inliner.html)

Write out the HTML (or Inky code) that causes the issue.

**What did you expect to happen?**
a popup showing the html preview 
**What happened instead?**
The interface says Loading ... indifenitely, in the developer console the following error is shown:

inliner.html:1 Failed to load https://inky-direct.zurb.com/ink/skate-proxy.php: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://foundation.zurb.com' is therefore not allowed access. The response had HTTP status code 403.

**What email clients does this happen in?**

**Comment by adampajak** [comment] 2017-12-20 15:21
You are right - I have got the same issue.

**Comment by cassihl** [comment] 2018-01-22 21:28
I'm having the same issue.

**Comment by DanielRuf** [comment] 2019-12-20 06:58
Closing as duplicate of https://github.com/foundation/foundation-emails/issues/850

**Closed by DanielRuf** 2019-12-20 06:58 UTC
