### ISSUE TITLE
Inliner Task doesn't work

### ISSUE THREAD

**Issue by XmlmXmlmX** [foundation/foundation-emails#318] opened 2016-04-01 11:44 UTC
The [`inliner` task](https://github.com/zurb/foundation-emails-template/blob/master/gulpfile.babel.js#L92) doesn't do anything.

I use a [fresh and clean installed](https://github.com/zurb/foundation-emails-template#using-the-cli) app.

When 'debugging' (is there a way to debug babel-gulpfiles in windows?) with `console.log(mqCss);`, after [`mqCss`](https://github.com/zurb/foundation-emails-template/blob/master/gulpfile.babel.js#L94), it is filled with valid css.

My output still contains the `<link>` and all css selectors. But no inline styles and no failures.

I think it must be something with that [`lazypipe`](https://github.com/zurb/foundation-emails-template/blob/master/gulpfile.babel.js#L96).

_Environment: Windows_

**Comment by joshvito** [comment] 2016-04-05 13:30
I think I may be having a problem with the inliner task too.

@XmlmXmlmX , are you able to successfully run `npm start` ?

[I have a problem running it for a second time](https://github.com/zurb/foundation-emails/issues/325)

**Comment by Reon90** [comment] 2016-05-19 08:58
any updates? i have the same issue
Environment: Mac OS "foundation-emails": "2.1.0"

**Comment by madmod** [comment] 2016-05-19 20:48
Same issue here. I had to update Gulp to get the build process working and now lazypipe is failing. The author of lazypipe said that they wouldn't support Gulp 4, but the issue is re-opened now. [source](https://github.com/OverZealous/lazypipe/issues/14)

**Comment by DanielRuf** [comment] 2018-03-11 21:07
> Same issue here. I had to update Gulp to get the build process working and now lazypipe is failing. The author of lazypipe said that they wouldn't support Gulp 4, but the issue is re-opened now. source

I suggest locking to Gulp 3 as Gulp 4 introduced (breaking) changes.

**Comment by DanielRuf** [comment] 2019-11-01 18:11
Closing as we did not receivy any further reports and our setups worked so far.

**Closed as completed by DanielRuf** 2019-11-01 18:11 UTC
Labels: bug, zurb stack
