### ISSUE TITLE
Responsive Email Inliner rendering non-breaking spaces.

### ISSUE THREAD

**Issue by moehammoud** [foundation/foundation-emails#804] opened 2017-07-03 05:38 UTC
**How can we reproduce this bug?**
Using the inliner: http://foundation.zurb.com/emails/inliner-v2.html
Every instance of **`&#xA0;`** renders as **`&amp;nbsp;`**

**What did you expect to happen?**
I expect **`&#xA0;`** to render as **`&nbsp;`**

**What happened instead?**
Every instance of **`&#xA0;`** renders as **`&amp;nbsp;`**

**What email clients does this happen in?**
All of them.

**Comment by jakriese** [comment] 2017-07-10 17:30
I agree, this is driving me crazy. This tool should expect valid HTML.

**Comment by DanielRuf** [comment] 2018-03-11 21:42
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.

**Closed as completed** 2019-11-01 18:39 UTC
