### ISSUE TITLE
Ampersand

### ISSUE THREAD

**Issue by Elardzhi** [foundation/foundation-emails#802] opened 2017-06-29 21:47 UTC
The Inliner replaces & with  & amp;

**Comment by XAMelleOH** [comment] 2017-06-30 14:53
That is how you supposed to use & in html

**Comment by Elardzhi** [comment] 2017-07-01 00:40
My html contains & nbsp; and & in base64 string (image). What next?

**Comment by Elardzhi** [comment] 2017-07-01 00:41
HTML may contain   & amp;   already. After your transformation it will be    & amp;amp;

**Comment by missmatsuko** [comment] 2017-07-19 23:30
Are you putting a space before after "&" in your HTML entities? It shouldn't have a space. I used `&amp;` and `&nbsp;` and `&copy;` and they were fine.

**Comment by davehoran** [comment] 2017-07-20 01:30
I have used several codes, as @missmatsuko shows above, and they all work fine.

**Comment by stephencrowther** [comment] 2017-07-26 16:43
This is happening to me on the website inliner v2

&nbsp;       becomes       &amp;nbsp;
&gt;       becomes       &amp;gt;

etc

Also - is this even maintained anymore?????

- Still moves <style> inside body when it should now be left in the <head>
- And still removes stuff like @font-face & :hover decs/elements so have to copy these back in afterwards

Not sure how people get round this when using a more automated approach - i do manually

**Comment by meganbosh** [comment] 2017-09-08 17:04
I've been having this issue, too. I'm finding that the issue isn't with the web inliner though, the issue is my editor (Dreamweaver, in this case). Dreamweaver is converting the ampersand to &amp;. Not sure what the fix is.
![inliner](https://user-images.githubusercontent.com/31774973/30222801-2d91e5d8-9496-11e7-8933-2202502a6e44.PNG)
![dreamweaver](https://user-images.githubusercontent.com/31774973/30222802-2d92cebc-9496-11e7-8d75-3ef68467d864.PNG)

**Comment by missmatsuko** [comment] 2017-09-08 17:42
I think this is related to #450 
I didn't see this issue, but I was using Inky.

**Comment by rafibomb** [comment] 2017-09-27 17:07
Is this happening when you click the copy to clipboard button?

**Comment by rafibomb** [comment] 2017-09-27 17:13
The inliner used is inline-css. There is a suggested solution here: jonkemp/inline-css#41

**Comment by meganbosh** [comment] 2017-10-03 13:41
Looks like everything copies ok if I don’t use the copy button. I manually selected (click and drag) copied all the code and pasted it into dreamweaver and the code was fine. 

One more issue (that I haven’t looked that deeply for a solution yet) is that when I use the collapse class, padding gets put back in, but that’s easy enough to fix after inlining since I’m usually doing it for a full width image.

**Comment by stephencrowther** [comment] 2017-10-13 16:14
I’ve just used this tool again for a newsletter and the ampersand issue doesn’t seem to occur now. Copy button doesn’t work in safari, I have to manually copy from the results box.

Still puts style block inside the body tag rather than the head tag though. And omits font face info, css animations, anchor tag :hover styling etc which have to be manually re-inserted again afterwards.

**Comment by hardcodet** [comment] 2017-10-24 21:03
Confirmed: Manually copying works, using the `Copy` button messes up the tags.

**Comment by stephencrowther** [comment] 2017-10-24 21:08
In safari the copy button doesn’t do anything, I’ve always manually selected and copied. When I first mentioned this problem I was doing it this way too. Think the inliner has had something done to it as seems fine now. My fav inliner as others seem to cause problems with code...

But... for god sake stop putting style tags in body!!!!!!

... and removing :hover elements

**Comment by DanielRuf** [comment] 2018-03-11 21:33
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.

**Closed as completed** 2019-11-01 18:39 UTC
