### ISSUE TITLE
Outlook Web App - text-align

### ISSUE THREAD

**Issue by acemichael** [foundation/foundation-emails#488] opened 2016-06-22 22:11 UTC
Outlook Web App overrides text-align:left to text-align: justify.

Original Code:

`<table class="row" style="border-collapse: collapse; border-spacing: 0; display: table; padding: 0; position: relative; text-align: left; vertical-align: top; width: 100%;">`

Outlook Web App Code: 

`<table width="100%" dir="rtl" style="border-collapse:collapse;border-spacing:0;width:100%;text-align:justify;padding:0;">`

**What email clients does this happen in?**
Outlook Web App

**Comment by rafibomb** [comment] 2016-06-23 17:03
Hmm, haven't heard of this one before. Have you seen or heard of a work-around?

**Comment by rafibomb** [comment] 2016-06-23 17:45
Does the this change actually affect content in the `<td>`? Do you have a test that shows a real world change?

Testing in Litmus, not seeing it happen
<img width="731" alt="screen shot 2016-06-23 at 10 56 01 am" src="https://cloud.githubusercontent.com/assets/5652085/16314102/2f2a9eb0-3931-11e6-913b-32c84f72f3ff.png">

**Comment by acemichael** [comment] 2016-06-23 18:08
Here's the screenshot from Outlook 2007 

![screen shot 2016-06-23 at 10 56 41 am](https://cloud.githubusercontent.com/assets/20098987/16314209/ab414c2e-3931-11e6-8ddf-3be209cd5426.png)

Screenshot from Outlook Web App:

![screen shot 2016-06-23 at 10 57 17 am](https://cloud.githubusercontent.com/assets/20098987/16314246/ca46692e-3931-11e6-8eea-36f440eb6e3b.png)

Here's the code from Outlook Web App: 

```
<table width="100%" dir="ltr" style="border-collapse:collapse;border-spacing:0;width:100%;text-align:justify;padding:0;">
<tbody>
<tr style="padding:0;">
<td style="margin:0;padding:0;">
<font face="Helvetica,Arial,sans-serif" size="2" color="#0A0A0A">
<span style="font-size:16px;font-weight:normal;">
<div style="margin:0 0 10px 0;padding:0;"><font face="Helvetica,Arial,sans-serif"><a href="redir.aspx?C=kRm8eg6175C76Y3lBlvxMRDObWa3graGgP_sOYDjFa8K4mCj5vTCA..&amp;URL=https%3a%2f%2fwww.pomona.edu%2fnews%2f2016%2f04%2f07-theatre-production-urinetown-inspiration-four-senior-theses" target="_blank">
<font face="Helvetica,Arial,sans-serif" color="#20438F">Theatre Production "Urinetown" the Inspiration for Four Senior Theses</font></a></font></div>
<div style="margin:0 0 10px 0;padding:0;"><font face="Helvetica,Arial,sans-serif">Lorem ipsum Dolore mollit incididunt qui in qui pariatur do deserunt est veniam voluptate tempor cillum labore sit. Lorem ipsum Nostrud labore sit laboris Excepteur. Lorem ipsum
Nostrud labore sit laboris. 
<a href="redir.aspx?C=kRm8eg6175C76Y3lBlvxMRDObWa3graGgP_sOYDjFa8K4mCj5vTCA..&amp;URL=https%3a%2f%2fwww.pomona.edu%2fnews%2f2016%2f04%2f07-theatre-production-urinetown-inspiration-four-senior-theses" target="_blank">
<font face="Helvetica,Arial,sans-serif" color="#20438F">MORE</font></a></font></div>
</span>
</font>
</td>
<td width="0" style="width:0;margin:0;padding:0;"><font face="Helvetica,Arial,sans-serif" size="2" color="#0A0A0A"><span style="font-size:16px;font-weight:normal;"></span></font></td>
</tr>
</tbody></table>  
```

Original Code:

```
<table style="border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; width: 100%; direction: ltr;">
<tbody>
<tr style="padding: 0; text-align: left; vertical-align: top;">
<th style="Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 19px; margin: 0; padding: 0; text-align: left;">
<p style="Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 19px; margin: 0; margin-bottom: 10px; padding: 0; text-align: left;"><a href="https://www.pomona.edu/news/2016/04/07-theatre-production-urinetown-inspiration-four-senior-theses"style="Margin: 0; color: #20438f; font-family: Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; text-decoration: none;">Theatre Production "Urinetown" the Inspiration for Four Senior Theses</a></p>
<p style="Margin: 0; Margin-bottom: 10px; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 19px; margin: 0; margin-bottom: 10px; padding: 0; text-align: left;">Lorem ipsum Dolore mollit incididunt qui in qui pariatur do deserunt est veniam voluptate tempor cillum labore sit. Lorem ipsum Nostrud labore sit laboris Excepteur. Lorem ipsum Nostrud labore sit laboris. <a href="https://www.pomona.edu/news/2016/04/07-theatre-production-urinetown-inspiration-four-senior-theses"style="Margin: 0; color: #20438f; font-family: Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: left; text-decoration: none;">MORE</a></p>
</th>
<th class="expander"style="Margin: 0; color: #0a0a0a; font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-weight: normal; line-height: 19px; margin: 0; padding: 0 !important; text-align: left; visibility: hidden; width: 0;"></th>
</tr>
</tbody>
</table>
```

**Comment by rafibomb** [comment] 2016-06-28 16:39
Are you using the Foundation for Email's CSS? There is CSS to "normalize" cross client issues like this. After 100's of tests on different templates, we're not able to replicate this. Can you make sure you're using Foundation for Emails CSS and let us know what you find - Thanks!

**Comment by rafibomb** [comment] 2016-07-05 21:04
@acemichael We're not able to replicate this. We'll close this here. If you can replicate this in Foundation for Emails please submit a new issue with a test case we can reproduce it on. Thanks!

**Closed as completed by rafibomb** 2016-07-05 21:04 UTC

**Comment by johnwctj** [comment] 2017-02-25 17:33
I'm having the same problem - to be clear, it isn't outlook in the web browser, it is the outlook application (both on android and iPhone, which they call the "Outlook Web App"). I am using the foundation-emails.css and it still produces justified text like acemichael describes above.

**Comment by neerajsohal** [comment] 2017-06-22 09:54
I can confirm that this issue is happening on Outlook 2016 (Windows 10) and on Outlook Android Application.

Also, it is weird because when you do a litmus test, the previews appear to be correctly formatted.
