### ISSUE TITLE
linear-gradient inlining incorrectly

### ISSUE THREAD

**Issue by hirish** [foundation/foundation-emails#326] opened 2016-04-05 15:18 UTC
**How can we reproduce this bug?**

HTML:

```
<div class="test">Hi</div>
```

CSS:

```
.test {
  background: linear-gradient(to bottom, red 0%, green 100%)
}
```

**What did you expect to happen?**

```
<div class="test" style="background: linear-gradient(to bottom,red 0%,green 100%);">Hi</div>
```

**What happened instead?**

Generates an invalid CSS linear-gradient:

```
<div class="test" style="background: linear-gradient(tobottom,red0%,green100%);">Hi</div>
```

**Comment by DanielRuf** [comment] 2019-12-19 07:02
Closing as duplicate of #918

**Closed as completed by DanielRuf** 2019-12-19 07:02 UTC
Labels: bug, inliner
