### ISSUE TITLE
Method to retain {{ Twig }} variables in HTML templates?

### ISSUE THREAD

**Issue by j-greig** [foundation/foundation-emails#931] opened 2018-12-05 14:11 UTC
Similar to https://github.com/zurb/foundation-emails/issues/537, I'm looking for a way to keep Twig tags in email templates, eg {{ order.id }} and various other variables.

I've tried wrapping in <raw> tags but that doesn't work.

Is there any other way to ignore sections of code in the HTML templates?

**Comment by DanielRuf** [comment] 2018-12-05 21:02
Did you try `<raw>`?

https://github.com/zurb/inky/search?q=raw&unscoped_q=raw
https://travis-ci.org/zurb/inky/jobs/223735994#L834

**Comment by DanielRuf** [comment] 2018-12-05 21:03
Also please provide some info about the foundation-emails and inky version and how your input and output looks like.

**Comment by j-greig** [comment] 2018-12-06 14:48
Thanks @DanielRuf!

I tried wrapping in a <raw> tag but that didn't seem to work...

Input:
`<h1>Order Confirmation <raw>{{ order.id }}</raw></h1>`

Output:
`<h1>Order Confirmation </h1>`

(And if the input is `<raw>{{ order.id }}</raw>` the output is blank)

Inky v1.3.7
Foundation Emails v2.2.1

**Comment by DanielRuf** [comment] 2018-12-06 14:54
Can you provide a simple JS file + package.json so we can reproduce and test this?

**Comment by j-greig** [comment] 2018-12-06 16:23
Just noticed that `src/emails/src/helpers/raw.js` appears to be empty/default... what should be in here?

```/**
 * Any code used inside this helper is ignored by Handlebars. Use it if your email service provider uses a Handlebars-like syntax.
 * @example
 * {{{{raw}}}}
 * {{ this }} code won't be parsed.
 * {{{{/raw}}}}
 */
module.exports = function(content) {
  return content.fn();
}
```

**Comment by DanielRuf** [comment] 2018-12-06 17:01
It's the helper from https://github.com/zurb/foundation-docs/blob/develop/helpers/raw.js

**Comment by DanielRuf** [comment] 2018-12-06 17:03
We can only try to create a unit test to see if that cafches the issue and a fix which makes it succeed.

**Comment by DanielRuf** [comment] 2018-12-06 17:04
We can try to create a unit test to see if that catches the issue and a fix which makes it succeed.

**Comment by petersvegrup** [comment] 2018-12-30 14:38
Not sure if the {{{raw}}} method solved it for you? Otherwise I can recommend a simple escape that I've been using successfully.

For ex `\{{ order.id }}`

EDIT: Added an extra pair of {} to correctly represent the helper, thanks @DanielRuf

**Comment by DanielRuf** [comment] 2018-12-30 14:44
I guess you mean `{{{{raw}}}}` which can be also used instead of `<raw>`.

**Comment by rickydazla** [comment] 2019-03-28 05:28
`{{{{raw}}}}{{ twig_variable }}{{{{/raw}}}}` is the code you are looking for :octocat:

**Comment by DanielRuf** [comment] 2019-12-19 05:28
Closing as we did not receive further feedback and this might be already solved.

**Closed as completed by DanielRuf** 2019-12-19 05:28 UTC
